### ISSUE TITLE
4.10.1 build error

### ISSUE THREAD

**Issue by forgandenny** [jonapoul/tak-geocoder-plugin#5]
When running `./gradlew app:installCivDebug` I get `Could not find com.atakmap.gradle:atak-gradle-takdev:2.4.1-debug3`

It probably expects to find `maven/com/atakmap/gradle/atak-gradle-takdev/2.4.1-debug3/atak-gradle-takdev-2.4.1-debug3.pom` in my local maven -- where can I get it from?

**Comment by jonapoul** [comment]
Ah sorry - that's a local fork I hacked together a while ago. I'll push it up to jitpack a bit later today, so you should get access to it.

**Comment by jonapoul** [comment]
Should be sorted, just change the takdev plugin declaration like here: https://github.com/jonapoul/tak-geocoder-plugin/commit/230427c0ae50fb572b124320e5b9a764f8df70eb
