### ISSUE TITLE
3rd party pipeline build errors

### ISSUE THREAD

**Issue by forgandenny** [jonapoul/tak-geocoder-plugin#6]
Local built to a device works, but third party pipeline fails with the following errors

![Screenshot 2023-09-01 at 00 03 56](https://github.com/jonapoul/tak-geocoder-plugin/assets/2554234/c96d38c2-2794-4a70-b901-27452027eb5e)

**Comment by jonapoul** [comment]
Apologies, just pushed up a fix. Didn't bother testing my changes last night against the good ol' pipeline - I should know better 😄

**Comment by forgandenny** [comment]
Pipeline builds but it crashes when loading apk in ATAK 

![Screenshot 2023-09-01 at 23 25 45](https://github.com/jonapoul/tak-geocoder-plugin/assets/2554234/8e0c9046-860c-419d-aa72-1526c2aa1d8d)

**Comment by jonapoul** [comment]
Just tried it on my end, works fine with both versions. Can you send over the APK? Did you make any other changes before pushing it up?

**Comment by forgandenny** [comment]
I've just tried it with the production version of ATAK 4.10.0.8 and it loads the plugin.

It only crashes in developer build of ATAK - both vanilla build from your master branch and the one with my modifications.

Is there any way to send you my apk privately?

**Comment by jonapoul** [comment]
I'm gonna guess you're trying to install a release plugin build on a debug ATAK build, or vice versa. They need to match up.

**Comment by forgandenny** [comment]
Wasn't aware of that, it makes sense!
